version: "3.3"
services:
  db: # база
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: QQww1122
      MYSQL_DATABASE: test1
      MYSQL_USER: test1
      MYSQL_PASSWORD: QQww1122
    ports:
      – "8514:8514"
    volumes:
      – db:/var/lib/mysql

 mvn: # сборка
    build: mvn_d
    volumes:
      - type: volume
        source: webapps
        target: /tmp/webapps

 web:
   image: tomcat
   ports:
      - '8080:8080'
   volumes_from:
     -mvn
     -db

volumes:
  webapps:
volumes:
  db: