---
version: '3.6'
services:
  db: # база
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: QQww1122
      MYSQL_DATABASE: test1
      MYSQL_USER: test1
      MYSQL_PASSWORD: QQww1122
    ports:
      - '8515:8514'
    volumes:
      - type: volume
        source: db
        target: /var/lib/mysql

  mvn:
    build: mvn_d
    volumes:
      - type: volume
        source: webapps
        target: /tmp/webapps

  web:
    image: tomcat:9
    ports:
      - '8080:8080'
    volumes:
      - type: volume
        source: webapps
        target: /usr/local/tomcat/webapps/App42PaaS-Java-MySQL-Sample-0.0.1-SNAPSHOT.war

volumes:
  webapps:
  db: