---
- name: install mvn
  hosts: mvn
  become: yes

  tasks:
    - name: Ensure git is present
      apt:
        name: git
        state: present

    - name: Ensure git is present
      apt:
        name: maven
        state: present

    - name: Read-write git checkout from github
      ansible.builtin.git:
        repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
        dest: /tmp/boxfuse-sample-java-war-hello

    - name: build
      shell: mvn package -f /tmp/boxfuse-sample-java-war-hello
- name: install tomcat9
  host: web
  become: yes

  tasks:
    - name: Ensure java
      apt: default-jdk
      state: present

    - name: Ensure tomcat9 is present
      apt:
        name: tomcat9
        state: present

    - name: Ensure tomcat star
      service:
        name: tomcat
        state: started

- hosts: mvn
  tasks:
    - name: Transfer file from mvn to web
      synchronize:
        src: /tmp/boxfuse-sample-java-war-hello/target/hello-1.0.war
        dest: /usr/local/tomcat/webapps
        mode: pull
      delegate_to: 130.193.50.69 #web