---
- hosts: localhost
  vars:
    keypair: key3-test
    instance_type: t2.micro
    security_group: MyGroup3
    image: ami-0fb653ca2d3203ac1
    region: us-east-2

  tasks:
  - name: Create a security group in AWS
    ec2_group:
      name: "{{ security_group }}"
      description: allow 22 port
      region: "{{ region }}"f
      rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0

  - name: Create an EC2 key
    ec2_key:
      name: "{{ keypair }}"
      region: "{{ region }}"
    register: ec2_key

  - name: Save private key
    copy:
      content: "{{ ec2_key.key.private_key }}"
      dest: "{{ ansible_env.HOME }}/.ssh/key2-test.pem"
      mode: 0600
    when: ec2_key.changed

  - name: Create instance 1
    ec2:
      key_name: "{{ keypair }}"
      group: "{{ security_group }}"
      region: "{{ region }}"
      instance_type: "{{ instance_type }}"
      image: "{{ image }}"
      wait: yes
      volumes:
        - device_name: /dev/sdh
          volume_size: 15
      count: 1
    register: ec2

  - name: add ec2 instance to hosts1
    add_host:
      hostname: "{{ item.public_ip }}"
      groupname: mvn
      ansible_private_key_file: ~/.ssh/key3-test.pem
    loop: "{{ ec2.instances }}"

- name: install mvn
  hosts: mvn
  become: yes

  tasks:
    - name: Ensure git is present
      apt:
        name: git
        state: present

    - name: Ensure git is present
      apt:
        name: maven
        state: present

    - name: Read-write git checkout from github
      ansible.builtin.git:
        repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
        dest: /tmp/boxfuse-sample-java-war-hello

    - name: build
      shell: mvn package -f /tmp/boxfuse-sample-java-war-hello
