---
- hosts: localhost
  vars:
    keypair: mykey2
    instance_type: t2.micro
    security_group: MyGroup2
    image: ami-0fb653ca2d3203ac1
    region: us-east-2

  tasks:
  - name: Create a security group in AWS
    ec2_group:
      name: MyGroup2
      description: allow 22 port
      region: "{{ region }}"
      rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0

  - name: Create an EC2 key
    ec2_key:
      name: mykey2
      region: "{{ region }}"
    register: ec2_key

  - name: Save private key
    copy:
      content: "{{ ec2_key.key.private_key }}"
      dest: "~/.ssh/id_rsa"
      mode: 0600
    when: ec2_key.changed

  - name: Create instance 1
    ec2:
      key_name: "{{ keypair }}"
      group: "{{ security_group }}"
      region: "{{ region }}"
      instance_type: "{{ instance_type }}"
      image: "{{ image }}"
      network:
        assign_public_ip: true
      wait: yes
      volumes:
        - device_name: /dev/sdh
          volume_size: 15
      count: 1
    register: ec2

  - name: add ec2 instance to hosts
    add_host:
      hostname: "{{ item.public_ip }}"
      groupname: bild
      region: "{{ region }}"
    loop: "{{ ec2.instances }}"