---
# tasks file for web
- name: install packages web
  apt: name={{ item }} state=present
  with_items:
       - default-jdk
       - tomcat9

- name: Ensure tomcat star
  service:
   name: tomcat9
   state: started