version: "3.6"
services:
  mvn:
    build: mvn_dock_f
    volumes:
      - type: volume
        source: webapps
        target: /tmp/webapps
  web:
    image: tomcat:9
    ports:
      - '8080:8080'
    volumes:
      - type: volume
        source: webapps
        target: /usr/local/tomcat/webapps

volumes:
  webapps: